name = "chat-worker"
main = "src/index.ts"
compatibility_date = "2025-02-04"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]

# Durable Objects 绑定
[[durable_objects.bindings]]
name = "Chat"
class_name = "Chat"

[[durable_objects.bindings]]
name = "USERSESSION"
class_name = "UserSession"
script_name = "auth-worker"

[[durable_objects.bindings]]
name = "APIUSAGE"
class_name = "ApiUsage"
script_name = "auth-worker"

# Durable Objects 迁移
[[migrations]]
tag = "v2"
new_classes = ["Chat"]

# KV绑定
[[kv_namespaces]]
binding = "CHAT_CACHE"
id = "48a9d87921df46eb9a5d9bf71302b83d"
preview_id = "e073d6bb683145ca971c0dc3790c787b"

[observability]
enabled = true
head_sampling_rate = 1 